local remap = require("Arduino-Nvim.remap")
local commands = require("Arduino-Nvim.commands")
local b_config = require("Arduino-Nvim.board_config")
require("Arduino-Nvim.libGetter")
local M = {}

b_config.load_or_create_config()
remap.load_keymaps()

vim.api.nvim_create_user_command("InoSelectBoard", function()
	commands.select_board_gui()
end, {})
vim.api.nvim_create_user_command("InoSelectPort", function()
	commands.select_port_gui()
end, {})
vim.api.nvim_create_user_command("InoCheck", function()
	commands.check()
end, {})
vim.api.nvim_create_user_command("InoGUI", function()
	commands.gui()
end, {})
vim.api.nvim_create_user_command("InoMonitor", function()
	commands.monitor()
end, {})
vim.api.nvim_create_user_command("InoSetBaud", function(opts)
	b_config.set_baudrate(opts.args)
end, { nargs = 1 })
vim.api.nvim_create_user_command("InoUpload", function()
	commands.upload()
end, {})
vim.api.nvim_create_user_command("InoUploadSlow", function()
	commands.baudrate = "1200"
	vim.notify("Trying upload with 1200 baud rate...", vim.log.levels.INFO)
	commands.upload()
end, {})
vim.api.nvim_create_user_command("InoUploadReset", commands.upload_reset, {})
vim.api.nvim_create_user_command("InoDebugUpload", commands.upload_debug, {})
vim.api.nvim_create_user_command("InoStatus", function()
	b_config.board_config_status()
end, {})
vim.api.nvim_create_user_command("InoList", function()
	commands.InoList()
end, {})
return M
